<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newsfields"
 *
 * Auto generated by Extension Builder 2013-07-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FE-User as newsauthor',
	'description' => 'Add a relation to fe_users to select a frontenduser as news author.',
	'category' => 'be',
	'author' => 'Georg Ringer',
	'author_email' => '',
	'author_company' => 'Cyberhouse GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '',
			'fluid' => '',
			'typo3' => '4.5',
			'news' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>